### ISSUE TITLE
this requires 1.20.1

### ISSUE THREAD

**Issue by Dabbpool** [nat212/steppy#1]
ive been asking around and trying to learn fabric just to get the stepup mod in 1.20 and i was so happy to see you did it already but its saying that i need to have 1.20.1 like many other mods so it seems like an issue in the system but ty sooo much for making this, i cant wait to use it, theres so many mods in the same spot and might die. now im waiting on invintory tabs, mod settings, rpg hud and so many more that might not be ported

**Comment by nat212** [comment]
Hmm, it wasn't my intention for this to be 1.20.1 only. I'll see if I can get that sorted, thanks

**Comment by nat212** [comment]
Fixed in version 1.0.1
