### ISSUE TITLE
(steppy-1.20-1.0.1) should be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by Zorklis** [nat212/steppy#2]
For a long time I was not bothering to test if Steppy was compatible until I decided to test it right now and it just works!
I don't remember if there was a toggle in the hotkeys menu but other than that not being present, it works :)

**Comment by nat212** [comment]
Great, thanks! I'll mark it as such

**Comment by nat212** [comment]
Marked as 1.20.2 compatible on Modrinth. If the mod itself needs to be marked as such as well, please let me know! :)
